import type {
  UserProfile, Lead, Contact, Company, Project, Task, Service, HostingAccount,
  Invoice, Payment, Ticket, ActivityItem, Requisition, Goal, Feedback, AppNotification,
  PayrollRecord, StaffShift, StaffMemo, ShiftTask
} from './types';

export const initialProfiles: UserProfile[] = [
  { id: 'u1', email: 'info@modedigitalcreations.ng', password: 'password123', full_name: 'Davids Ogan', role: 'managing_director', department: 'Executive', job_title: 'Managing Director & Super Admin', phone: '+234 801 234 5678', is_active: true, hasPayrollAccess: true },
  { id: 'u2', email: 'chioma@modedigitalcreations.ng', password: 'password123', full_name: 'Chioma Eze', role: 'sales', department: 'Sales & Growth', job_title: 'Head of Sales', phone: '+234 802 345 6789', is_active: true },
  { id: 'u3', email: 'emeka@modedigitalcreations.ng', password: 'password123', full_name: 'Emeka Nwosu', role: 'developer', department: 'Engineering', job_title: 'Senior Full-Stack Engineer', phone: '+234 803 456 7890', is_active: true },
  { id: 'u4', email: 'fatima@modedigitalcreations.ng', password: 'password123', full_name: 'Fatima Bello', role: 'manager', department: 'Operations', job_title: 'Operations & Project Manager', phone: '+234 804 567 8901', is_active: true },
  { id: 'u5', email: 'ibrahim@modedigitalcreations.ng', password: 'password123', full_name: 'Ibrahim Musa', role: 'administration', department: 'Administration', job_title: 'Administration & Finance Lead', phone: '+234 805 678 9012', is_active: true, hasPayrollAccess: true },
  { id: 'u6', email: 'admin@modewebhost.com.ng', password: 'password123', full_name: 'Mode Web Host Admin', role: 'managing_director', department: 'Executive & Systems', job_title: 'Super Admin & Lead Hostmaster', phone: '+234 801 888 9999', is_active: true, hasPayrollAccess: true },
  { id: 'u7', email: 'ben@modewebhost.com.ng', password: 'password123', full_name: 'Ben Asiedu', role: 'employee', department: 'Web Hosting & Support', job_title: 'Hosting & Technical Support Specialist', phone: '+234 802 888 7777', is_active: true, hasPayrollAccess: false },
];

export const initialLeads: Lead[] = [
  { id: 'l1', name: 'Chukwudi Abiola', company: 'TechVenture Nigeria', email: 'chukwudi@techventure.ng', phone: '+234 810 111 2222', serviceInterested: 'website-development', source: 'website', budget: 1500000, currency: 'NGN', notes: 'Interested in a corporate portal with CMS', status: 'new-lead', estimatedValue: 1500000, probability: 20, expectedCloseDate: '2026-10-15', assignedTo: 'u2', createdAt: '2026-06-01' },
  { id: 'l2', name: 'Amina Yusuf', company: 'Sahara Logistics', email: 'amina@saharalog.com', phone: '+234 811 222 3333', serviceInterested: 'ecommerce-development', source: 'facebook-ads', budget: 3200000, currency: 'NGN', notes: 'Needs e-commerce logistics supplies checkout', status: 'qualified', estimatedValue: 3200000, probability: 40, expectedCloseDate: '2026-10-30', assignedTo: 'u2', createdAt: '2026-05-20' },
  { id: 'l3', name: 'Olufemi Peters', company: 'EduFirst Academy', email: 'olufemi@edufirst.ng', phone: '+234 812 333 4444', serviceInterested: 'lms-development', source: 'google-ads', budget: 5500000, currency: 'NGN', notes: 'LMS for 650+ students with ModeCBT integration', status: 'discovery-call', estimatedValue: 5500000, probability: 60, expectedCloseDate: '2026-10-15', assignedTo: 'u4', createdAt: '2026-05-10' },
  { id: 'l4', name: 'Grace Obi', company: 'HealthPlus Clinics', email: 'grace@healthplus.ng', phone: '+234 813 444 5555', serviceInterested: 'custom-software', source: 'referral', budget: 8500000, currency: 'NGN', notes: 'Clinic management system with patient portal', status: 'proposal-sent', estimatedValue: 8500000, probability: 70, expectedCloseDate: '2026-10-01', assignedTo: 'u4', createdAt: '2026-04-25' },
  { id: 'l5', name: 'David Thompson', company: 'UK Trade Connect', email: 'david@uktrade.co.uk', phone: '+44 20 7946 0958', serviceInterested: 'website-development', source: 'website', budget: 6500000, currency: 'NGN', notes: 'UK-based corporate site for West Africa operations', status: 'negotiation', estimatedValue: 6500000, probability: 85, expectedCloseDate: '2026-09-30', assignedTo: 'u2', createdAt: '2026-04-10' },
  { id: 'l6', name: 'Ngozi Kalu', company: 'FashionHub Lagos', email: 'ngozi@fashionhub.ng', phone: '+234 814 555 6666', serviceInterested: 'ecommerce-development', source: 'whatsapp', budget: 2200000, currency: 'NGN', notes: 'Online fashion boutique with payment & delivery integration', status: 'won', estimatedValue: 2200000, probability: 100, expectedCloseDate: '2026-06-01', assignedTo: 'u2', createdAt: '2026-03-15' },
  { id: 'l7', name: 'Tunde Bakare', company: 'AgriTech Solutions', email: 'tunde@agritech.ng', phone: '+234 815 666 7777', serviceInterested: 'seo-services', source: 'manual', budget: 650000, currency: 'NGN', notes: 'SEO and content marketing for agro-exports', status: 'contacted', estimatedValue: 650000, probability: 35, expectedCloseDate: '2026-10-01', assignedTo: 'u2', createdAt: '2026-06-10' },
  { id: 'l8', name: 'John Smith', company: 'Global Ventures LLC', email: 'john@globalventures.com', phone: '+1 212 555 0199', serviceInterested: 'web-hosting', source: 'google-ads', budget: 3500000, currency: 'NGN', notes: 'Dedicated cloud hosting cluster for 12 websites', status: 'new-lead', estimatedValue: 3500000, probability: 20, expectedCloseDate: '2026-11-01', assignedTo: 'u2', createdAt: '2026-06-20' },
];

export const initialContacts: Contact[] = [
  { id: 'c1', name: 'Chukwudi Abiola', email: 'chukwudi@techventure.ng', phone: '+234 810 111 2222', company: 'TechVenture Nigeria', position: 'CEO & Founder', notes: 'Prefers WhatsApp updates on weekdays', isActive: true, createdAt: '2026-06-01' },
  { id: 'c2', name: 'Amina Yusuf', email: 'amina@saharalog.com', phone: '+234 811 222 3333', company: 'Sahara Logistics', position: 'VP Operations', notes: 'Requested demo of freight tracking', isActive: true, createdAt: '2026-05-20' },
  { id: 'c3', name: 'Olufemi Peters', email: 'olufemi@edufirst.ng', phone: '+234 812 333 4444', company: 'EduFirst Academy', position: 'Principal Administrator', notes: 'Needs exam schedule ready before term resumes', isActive: true, createdAt: '2026-05-10' },
  { id: 'c4', name: 'Grace Obi', email: 'grace@healthplus.ng', phone: '+234 813 444 5555', company: 'HealthPlus Clinics', position: 'Medical Director', notes: 'Strict HIPAA and NDPR compliance requirements', isActive: true, createdAt: '2026-04-25' },
  { id: 'c5', name: 'Ngozi Kalu', email: 'ngozi@fashionhub.ng', phone: '+234 814 555 6666', company: 'FashionHub Lagos', position: 'Creative Director', notes: 'Active client, fast turnaround expected', isActive: true, createdAt: '2026-03-15' },
  { id: 'c6', name: 'David Thompson', email: 'david@uktrade.co.uk', phone: '+44 20 7946 0958', company: 'UK Trade Connect', position: 'Head of West Africa Desk', notes: 'Requires NGN invoicing and wire receipts', isActive: true, createdAt: '2026-04-10' },
];

export const initialCompanies: Company[] = [
  { id: 'co1', name: 'TechVenture Nigeria', industry: 'FinTech / SaaS', website: 'https://techventure.ng', email: 'info@techventure.ng', phone: '+234 810 111 2222', address: '15 Admiralty Way, Lekki Phase 1, Lagos', contactIds: ['c1'], createdAt: '2026-06-01' },
  { id: 'co2', name: 'Sahara Logistics', industry: 'Logistics & Supply Chain', website: 'https://saharalog.com', email: 'operations@saharalog.com', phone: '+234 811 222 3333', address: '42 Marina Road, Lagos Island, Lagos', contactIds: ['c2'], createdAt: '2026-05-20' },
  { id: 'co3', name: 'EduFirst Academy', industry: 'Education', website: 'https://edufirst.ng', email: 'admin@edufirst.ng', phone: '+234 812 333 4444', address: '8 University Crescent, Bodija, Ibadan, Oyo', contactIds: ['c3'], createdAt: '2026-05-10' },
  { id: 'co4', name: 'HealthPlus Clinics', industry: 'Healthcare', website: 'https://healthplus.ng', email: 'contact@healthplus.ng', phone: '+234 813 444 5555', address: '22 Awolowo Road, Ikoyi, Lagos', contactIds: ['c4'], createdAt: '2026-04-25' },
  { id: 'co5', name: 'FashionHub Lagos', industry: 'Retail & Fashion', website: 'https://fashionhub.ng', email: 'orders@fashionhub.ng', phone: '+234 814 555 6666', address: '5 Allen Avenue, Ikeja, Lagos', contactIds: ['c5'], createdAt: '2026-03-15' },
];

export const initialProjects: Project[] = [
  { id: 'p1', name: 'FashionHub E-commerce Store', description: 'Complete online store with Paystack, inventory sync, and dispatch API', clientName: 'Ngozi Kalu', clientId: 'c5', serviceType: 'ecommerce-development', status: 'in-progress', startDate: '2026-06-05', endDate: '2026-09-30', budget: 2200000, currency: 'NGN', progress: 45, assignedTeam: ['u3', 'u4'], dealId: 'l6', createdAt: '2026-06-05' },
  { id: 'p2', name: 'MODE Ops Suite Redesign', description: 'Consolidation of CRM, Expense Requisitions, and OMM into Next.js App Router', clientName: 'MODE Digital Internal', clientId: 'c1', serviceType: 'custom-software', status: 'in-progress', startDate: '2026-06-01', endDate: '2026-08-30', budget: 1500000, currency: 'NGN', progress: 75, assignedTeam: ['u1', 'u3'], createdAt: '2026-06-01' },
  { id: 'p3', name: 'EduFirst CBT Testing Center', description: 'Deploy and test high-concurrency exam software for 650 candidates', clientName: 'Olufemi Peters', clientId: 'c3', serviceType: 'cbt-platform', status: 'pending', startDate: '2026-09-01', endDate: '2026-10-30', budget: 3500000, currency: 'NGN', progress: 10, assignedTeam: ['u3', 'u4'], createdAt: '2026-06-18' },
];

export const initialTasks: Task[] = [
  { id: 't1', projectId: 'p1', title: 'Product schema & Paystack webhook setup', description: 'Configure order state transitions on webhook confirmation', status: 'completed', priority: 'high', assignedTo: 'u3', dueDate: '2026-06-25', order: 1, createdAt: '2026-06-05' },
  { id: 't2', projectId: 'p1', title: 'Mobile responsive checkout UI', description: 'Ensure seamless single-page checkout on mobile devices', status: 'in-progress', priority: 'urgent', assignedTo: 'u3', dueDate: '2026-07-10', order: 2, createdAt: '2026-06-05' },
  { id: 't3', projectId: 'p2', title: 'Merge 3 database schemas into unified Supabase', description: 'Migrate CRM, Office-Expense, and OMM tables with RLS', status: 'completed', priority: 'urgent', assignedTo: 'u3', dueDate: '2026-09-26', order: 1, createdAt: '2026-06-01' },
  { id: 't4', projectId: 'p2', title: 'Integrate Requisition approval flow', description: 'Staff submission -> Manager approval -> Accounts receipt', status: 'in-progress', priority: 'high', assignedTo: 'u3', dueDate: '2026-09-27', order: 2, createdAt: '2026-06-01' },
];

export const initialShiftTasks: ShiftTask[] = [
  {
    id: 'st-1',
    staffId: 'u5',
    staffName: 'Ibrahim Musa',
    date: '2026-10-02',
    title: 'Audit and disburse approved Q3 marketing expense vouchers',
    priority: 'high',
    status: 'completed',
    completedAt: '2026-10-02T11:30:00Z',
    projectId: 'p1',
    projectName: 'FashionHub E-commerce Store',
    createdAt: '2026-10-02T08:30:00Z',
  },
  {
    id: 'st-2',
    staffId: 'u5',
    staffName: 'Ibrahim Musa',
    date: '2026-10-02',
    title: 'Reconcile Stanbic IBTC corporate account inflows for September',
    priority: 'urgent',
    status: 'pending',
    createdAt: '2026-10-02T08:35:00Z',
  },
  {
    id: 'st-3',
    staffId: 'u5',
    staffName: 'Ibrahim Musa',
    date: '2026-10-02',
    title: 'Prepare withholding tax schedule for external contractors',
    priority: 'medium',
    status: 'pending',
    carriedForwardFrom: '2026-10-01',
    createdAt: '2026-10-01T09:00:00Z',
  },
  {
    id: 'st-4',
    staffId: 'u1',
    staffName: 'Davids Ogan',
    date: '2026-10-02',
    title: 'Sign off pending expense requisitions and executive budget review',
    priority: 'urgent',
    status: 'completed',
    completedAt: '2026-10-02T10:15:00Z',
    createdAt: '2026-10-02T08:00:00Z',
  },
  {
    id: 'st-5',
    staffId: 'u1',
    staffName: 'Davids Ogan',
    date: '2026-10-02',
    title: 'Review proposal deck for Sahara Logistics fleet integration',
    priority: 'high',
    status: 'pending',
    createdAt: '2026-10-02T08:05:00Z',
  },
  {
    id: 'st-6',
    staffId: 'u3',
    staffName: 'Emeka Nwosu',
    date: '2026-10-02',
    title: 'Paystack webhook retry queue & idempotency key verification',
    priority: 'high',
    status: 'completed',
    completedAt: '2026-10-02T12:00:00Z',
    projectId: 'p1',
    projectName: 'FashionHub E-commerce Store',
    createdAt: '2026-10-02T09:00:00Z',
  },
  {
    id: 'st-7',
    staffId: 'u3',
    staffName: 'Emeka Nwosu',
    date: '2026-10-02',
    title: 'Mobile checkout single-page responsiveness testing on iOS',
    priority: 'urgent',
    status: 'pending',
    carriedForwardFrom: '2026-10-01',
    projectId: 'p1',
    projectName: 'FashionHub E-commerce Store',
    createdAt: '2026-10-01T09:30:00Z',
  },
];

export const initialServices: Service[] = [
  { id: 's1', name: 'Custom Website Development', type: 'website-development', description: 'Enterprise responsive web applications built with Next.js & Tailwind', basePrice: 650000, currency: 'NGN', isActive: true, features: ['Next.js Architecture', 'High Performance Core Web Vitals', 'CMS Integration', 'Enterprise SEO', 'Analytics & Tag Manager'] },
  { id: 's2', name: 'E-commerce Platforms', type: 'ecommerce-development', description: 'High-converting online storefronts with payment gateway integrations', basePrice: 1800000, currency: 'NGN', isActive: true, features: ['Product Catalog', 'Paystack / Flutterwave', 'Inventory Management', 'Order Tracking', 'Customer Portal'] },
  { id: 's3', name: 'Learning Management System (LMS)', type: 'lms-development', description: 'Scalable educational platforms with student and instructor dashboards', basePrice: 3500000, currency: 'NGN', isActive: true, features: ['Course Builder', 'Student Progress', 'Video Hosting', 'Automated Certification', 'Assignment Grading'] },
  { id: 's4', name: 'ModeCBT Examination Platform', type: 'cbt-platform', description: 'Ultra-reliable Computer-Based Testing platform for institutions', basePrice: 2500000, currency: 'NGN', isActive: true, features: ['Timed Exams', 'Randomized Questions', 'Offline-Resilient Architecture', 'Real-time Analytics', 'Tamper Resistance'] },
  { id: 's5', name: 'Managed Cloud Web Hosting', type: 'web-hosting', description: 'High-availability SSD hosting with daily automated backups and SSL', basePrice: 35000, currency: 'NGN', isActive: true, features: ['99.9% Uptime SLA', 'Free SSL Certificates', 'Automated Daily Backups', '24/7 Monitoring', 'cPanel & SSH Access'] },
  { id: 's6', name: 'Custom Software & APIs', type: 'custom-software', description: 'Tailored enterprise software, CRM, and cloud backend microservices', basePrice: 6000000, currency: 'NGN', isActive: true, features: ['System Architecture', 'Supabase / PostgreSQL', 'Secure REST & GraphQL APIs', 'Automated Tests', 'Cloud Deployment'] },
  { id: 's7', name: 'MODE Schools', type: 'custom-software', description: 'All-in-one School Management ERP with Student Information System, fee invoicing, and grade books', basePrice: 1500000, currency: 'NGN', isActive: true, features: ['Student Information System (SIS)', 'Termly Report Card Generator', 'Online Fee Payment & Receipts', 'Attendance & Staff Roster Tracking', 'Parent Portal & SMS Alerts', 'ModeCBT Platform Integration'] },
  { id: 's8', name: 'Domain Registration (.com)', type: 'domain-registration', description: 'Global commercial domain name registration with automated DNS management and free WHOIS privacy', basePrice: 25000, currency: 'NGN', isActive: true, features: ['Instant Automated Activation', 'Free DNS Management Zone', 'WHOIS Privacy Protection', 'Domain & Email Forwarding', '2FA Domain Lock Security'] },
  { id: 's9', name: 'Domain Registration (.ng)', type: 'domain-registration', description: 'Official Nigerian national ccTLD domain with accredited NiRA registry routing and high local SEO ranking', basePrice: 18000, currency: 'NGN', isActive: true, features: ['Official NiRA Registry Accreditation', 'Instant DNS Propagation', 'Premium Nigerian Brand Identity', 'Anycast Nameserver Network', 'Seamless Hosting Linking'] },
  { id: 's10', name: 'Domain Registration (.com.ng)', type: 'domain-registration', description: 'Cost-effective Nigerian business domain registration with complete DNS control and automated renewal', basePrice: 8500, currency: 'NGN', isActive: true, features: ['Affordable Local Business Identity', 'Instant Registry Verification', 'Free DNS & Zone Management', 'Email Forwarding Aliases', '1-Click WHMCS Provisioning'] },
  { id: 's11', name: 'CPanel Unlimited Hosting', type: 'web-hosting', description: 'Unlimited cPanel cloud hosting with unmetered NVMe SSD storage, unlimited databases, and corporate email accounts', basePrice: 65000, currency: 'NGN', isActive: true, features: ['Unmetered NVMe SSD Storage', 'Unlimited Business Email Accounts', 'Free AutoSSL Security Certificates', 'Unlimited MySQL Databases', '1-Click Softaculous App Installer', 'Daily Automated Remote Backups'] },
];

export const initialHostingAccounts: HostingAccount[] = [
  { id: 'h1', clientName: 'FashionHub Lagos', clientId: 'c5', domainName: 'fashionhub.ng', registrationDate: '2025-06-01', expiryDate: '2027-06-01', hostingPlan: 'business', sslStatus: 'active', autoRenew: true, status: 'active', monthlyFee: 18000, currency: 'NGN' },
  { id: 'h2', clientName: 'TechVenture Nigeria', clientId: 'c1', domainName: 'techventure.ng', registrationDate: '2025-03-15', expiryDate: '2026-10-15', hostingPlan: 'enterprise', sslStatus: 'active', autoRenew: true, status: 'active', monthlyFee: 35000, currency: 'NGN' },
  { id: 'h3', clientName: 'EduFirst Academy', clientId: 'c3', domainName: 'edufirst.ng', registrationDate: '2025-01-10', expiryDate: '2026-10-05', hostingPlan: 'business', sslStatus: 'active', autoRenew: false, status: 'active', monthlyFee: 18000, currency: 'NGN' },
  { id: 'h4', clientName: 'HealthPlus Clinics', clientId: 'c4', domainName: 'healthplus.ng', registrationDate: '2024-08-20', expiryDate: '2026-11-20', hostingPlan: 'enterprise', sslStatus: 'active', autoRenew: true, status: 'active', monthlyFee: 35000, currency: 'NGN' },
  { id: 'h5', clientName: 'Sahara Logistics', clientId: 'c2', domainName: 'saharalog.com', registrationDate: '2025-11-05', expiryDate: '2026-12-05', hostingPlan: 'starter', sslStatus: 'active', autoRenew: true, status: 'active', monthlyFee: 10000, currency: 'NGN' },
];

export const initialInvoices: Invoice[] = [
  { id: 'inv1', invoiceNumber: 'INV-2026-001', clientName: 'FashionHub Lagos', clientEmail: 'ngozi@fashionhub.ng', clientId: 'c5', projectId: 'p1', items: [{ id: 'ii1', description: 'E-commerce Platform Architecture & UI', quantity: 1, unitPrice: 900000, total: 900000 }, { id: 'ii2', description: 'Payment & Logistics API Integration', quantity: 1, unitPrice: 300000, total: 300000 }], subtotal: 1200000, tax: 90000, total: 1290000, amountPaid: 1290000, currency: 'NGN', status: 'paid', issueDate: '2026-06-05', dueDate: '2026-06-20', notes: 'Phase 1 development invoice — settled in full via Bank Transfer.', createdAt: '2026-06-05' },
  { id: 'inv2', invoiceNumber: 'INV-2026-002', clientName: 'FashionHub Lagos', clientEmail: 'ngozi@fashionhub.ng', clientId: 'c5', projectId: 'p1', items: [{ id: 'ii3', description: 'E-commerce Milestone 2: Final QA & Launch', quantity: 1, unitPrice: 910000, total: 910000 }], subtotal: 910000, tax: 68250, total: 978250, amountPaid: 0, currency: 'NGN', status: 'sent', issueDate: '2026-06-20', dueDate: '2026-07-15', notes: 'Milestone 2 final invoice.', createdAt: '2026-06-20' },
  { id: 'inv3', invoiceNumber: 'INV-2026-003', clientName: 'TechVenture Nigeria', clientEmail: 'chukwudi@techventure.ng', clientId: 'c1', items: [{ id: 'ii4', description: 'Annual Dedicated Cloud Hosting - Enterprise', quantity: 12, unitPrice: 35000, total: 420000 }], subtotal: 420000, tax: 31500, total: 451500, amountPaid: 451500, currency: 'NGN', status: 'paid', issueDate: '2026-03-15', dueDate: '2026-04-15', notes: 'Annual hosting cluster renewal.', createdAt: '2026-03-15' },
  { id: 'inv4', invoiceNumber: 'INV-2026-004', clientName: 'UK Trade Connect', clientEmail: 'david@uktrade.co.uk', clientId: 'c6', items: [{ id: 'ii5', description: 'International Trade Portal — Frontend & Enterprise System', quantity: 1, unitPrice: 4500000, total: 4500000 }], subtotal: 4500000, tax: 0, total: 4500000, amountPaid: 0, currency: 'NGN', status: 'draft', issueDate: '2026-06-20', dueDate: '2026-07-20', notes: 'Corporate invoice settled in Nigerian Naira.', createdAt: '2026-06-20' },
];

export const initialPayments: Payment[] = [
  { id: 'pay1', invoiceId: 'inv1', amount: 1290000, currency: 'NGN', method: 'bank-transfer', reference: 'TRF-MODE-20260610-884', date: '2026-06-10', notes: 'Stanbic IBTC confirmed deposit' },
  { id: 'pay2', invoiceId: 'inv3', amount: 451500, currency: 'NGN', method: 'paystack', reference: 'PSK-20260320-771', date: '2026-03-20', notes: 'Automatic card payment renewal' },
];

// ==========================================
// OFFICE EXPENSE: REQUISITIONS
// ==========================================
export const initialRequisitions: Requisition[] = [
  {
    id: 'req-1',
    receiptNumber: 'REQ-2026-1042',
    title: 'AWS Cloud Server & Database Monthly Subscription',
    description: 'Production infrastructure renewal for MODE CBT & client hosting droplets',
    amount: 145000,
    currency: 'NGN',
    category: 'Cloud Infrastructure',
    urgency: 'Urgent',
    status: 'Completed',
    staffName: 'Emeka Nwosu',
    staffId: 'u3',
    decisionNotes: 'Approved by MD. Essential for production stability.',
    decidedAt: '2026-06-22T10:15:00Z',
    decidedBy: 'Davids Ogan',
    completedAt: '2026-06-22T11:30:00Z',
    disbursedBy: 'Ibrahim Musa',
    transactionId: 'TXN-GTB-8839219',
    createdAt: '2026-06-22T08:30:00Z',
  },
  {
    id: 'req-2',
    receiptNumber: 'REQ-2026-1043',
    title: 'Quarterly Office Fiber Internet Subscription',
    description: 'Main office dedicated fiber link renewal (Swift Networks)',
    amount: 85000,
    currency: 'NGN',
    category: 'Office Utilities',
    urgency: 'High',
    status: 'Approved',
    staffName: 'Fatima Bello',
    staffId: 'u4',
    decisionNotes: 'Approved. Accounts to disburse via swift online portal.',
    decidedAt: '2026-06-24T14:00:00Z',
    decidedBy: 'Davids Ogan',
    createdAt: '2026-06-24T11:20:00Z',
  },
  {
    id: 'req-3',
    receiptNumber: 'REQ-2026-1044',
    title: 'Facebook Ads & Meta Campaign Budget (Q3)',
    description: 'Lead generation marketing spend targeting Nigerian education & e-commerce sectors',
    amount: 250000,
    currency: 'NGN',
    category: 'Marketing & Ads',
    urgency: 'Medium',
    status: 'Pending',
    staffName: 'Chioma Eze',
    staffId: 'u2',
    createdAt: '2026-06-25T09:45:00Z',
  },
  {
    id: 'req-4',
    receiptNumber: 'REQ-2026-1045',
    title: 'Ergonomic Developer Chair & Dual Monitor Mount',
    description: 'Hardware upgrade for senior developer engineering station',
    amount: 95000,
    currency: 'NGN',
    category: 'Equipment & Hardware',
    urgency: 'Low',
    status: 'Pending',
    staffName: 'Emeka Nwosu',
    staffId: 'u3',
    createdAt: '2026-06-25T16:10:00Z',
  },
];

// ==========================================
// ONE-MINUTE MANAGER: GOALS & FEEDBACK
// ==========================================
export const initialGoals: Goal[] = [
  {
    id: 'g1',
    manager_id: 'u1',
    manager_name: 'Davids Ogan',
    employee_id: 'u2',
    employee_name: 'Chioma Eze',
    objective: 'Generate 15 Qualified Enterprise Leads in Q3',
    expected_result: 'At least 5 proposals sent with total pipeline value exceeding ₦20,000,000',
    deadline: '2026-09-30',
    progress: 60,
    status: 'in_progress',
    strategy_status: 'approved',
    strategy_text: '1. Launch targeted LinkedIn outreach to private secondary school principals for ModeCBT.\n2. Follow up within 24 hours on all website contact form submissions.\n3. Host weekly product walkthrough webinars.',
    strategy_feedback: 'Approved! Excellent structured approach. Prioritize the schools in Lagos & Abuja first.',
    strategy_submitted_at: '2026-06-05T10:00:00Z',
    strategy_approved_at: '2026-06-06T09:30:00Z',
    created_at: '2026-06-01T08:00:00Z',
  },
  {
    id: 'g2',
    manager_id: 'u1',
    manager_name: 'Davids Ogan',
    employee_id: 'u3',
    employee_name: 'Emeka Nwosu',
    objective: 'Unify 3 Internal Codebases into Mode-Ops Next.js Architecture',
    expected_result: 'Zero duplicate auth stores, full Supabase integration, sub-100ms dashboard load times',
    deadline: '2026-08-30',
    progress: 80,
    status: 'in_progress',
    strategy_status: 'approved',
    strategy_text: '1. Merge Supabase schema across CRM, Expense, and OMM.\n2. Rebuild navigation with Next.js App Router and Tailwind v4.\n3. Preserve all existing business logic with offline-first client fallback.',
    strategy_feedback: 'Outstanding roadmap. Let us test with real production data immediately.',
    strategy_submitted_at: '2026-06-02T11:00:00Z',
    strategy_approved_at: '2026-06-02T15:00:00Z',
    created_at: '2026-06-01T08:00:00Z',
  },
  {
    id: 'g3',
    manager_id: 'u4',
    manager_name: 'Fatima Bello',
    employee_id: 'u5',
    employee_name: 'Ibrahim Musa',
    objective: 'Achieve Sub-30-Minute Support Ticket Resolution Time',
    expected_result: 'Customer satisfaction rating above 95% on all hosting and email enquiries',
    deadline: '2026-09-15',
    progress: 75,
    status: 'in_progress',
    strategy_status: 'approved',
    strategy_text: '1. Set up instant Discord/WhatsApp alerts for high-priority tickets.\n2. Pre-configure canned answers for domain renewal and DNS propagation.\n3. Daily morning ticket review.',
    strategy_feedback: 'Great. Make sure escalation procedures to Emeka are well documented.',
    strategy_submitted_at: '2026-06-10T12:00:00Z',
    strategy_approved_at: '2026-06-11T09:00:00Z',
    created_at: '2026-06-08T08:00:00Z',
  },
];

export const initialFeedbacks: Feedback[] = [
  {
    id: 'fb1',
    goal_id: 'g1',
    manager_id: 'u1',
    manager_name: 'Davids Ogan',
    employee_id: 'u2',
    employee_name: 'Chioma Eze',
    type: 'praise',
    details: 'One-Minute Praise: Chioma, your quick response to the UK Trade Connect inquiry secured our largest international project of the quarter! Exceptional professionalism and speed.',
    created_at: '2026-06-15T14:30:00Z',
  },
  {
    id: 'fb2',
    goal_id: 'g2',
    manager_id: 'u1',
    manager_name: 'Davids Ogan',
    employee_id: 'u3',
    employee_name: 'Emeka Nwosu',
    type: 'praise',
    details: 'One-Minute Praise: Emeka, the database schema consolidation was completely seamless. Zero downtime and beautifully formatted PostgreSQL tables. Thank you!',
    created_at: '2026-06-20T17:00:00Z',
  },
  {
    id: 'fb3',
    goal_id: 'g3',
    manager_id: 'u4',
    manager_name: 'Fatima Bello',
    employee_id: 'u5',
    employee_name: 'Ibrahim Musa',
    type: 'redirect',
    details: 'One-Minute Redirect: Ibrahim, noticed two renewal tickets from Sahara Logistics were left unreplied over the weekend. Remember to turn on weekend on-call coverage or auto-acknowledge the receipt so clients know we are on it.',
    created_at: '2026-06-22T09:15:00Z',
  },
];

export const initialTickets: Ticket[] = [
  { id: 'tk1', clientName: 'FashionHub Lagos', clientId: 'c5', subject: 'High-res product images uploading slow on checkout', description: 'When uploading images larger than 5MB, response time degrades. Needs Cloudinary / CDN optimization.', status: 'in-progress', priority: 'high', assignedTo: 'u3', createdAt: '2026-06-18' },
  { id: 'tk2', clientName: 'EduFirst Academy', clientId: 'c3', subject: 'Domain DNS MX record verification for custom email', description: 'Need Google Workspace verification TXT record added to domain DNS settings.', status: 'open', priority: 'medium', assignedTo: 'u5', createdAt: '2026-06-23' },
  { id: 'tk3', clientName: 'TechVenture Nigeria', clientId: 'c1', subject: 'SSL Certificate Auto-Renewal Confirmation', description: 'Confirm SSL certificate renewed properly on port 443 before product launch.', status: 'resolved', priority: 'low', assignedTo: 'u5', createdAt: '2026-06-12' },
];

export const initialActivities: ActivityItem[] = [
  { id: 'act-1', activity_type: 'crm_deal', description: 'FashionHub Lagos made full payment of ₦1,290,000 for Phase 1', entity_type: 'Invoice', entity_id: 'inv1', user_name: 'Chioma Eze', created_at: '2026-06-10 11:30' },
  { id: 'act-2', activity_type: 'expense_approval', description: 'Requisition REQ-2026-1042 (₦145,000) approved & disbursed for Cloud Servers', entity_type: 'Requisition', entity_id: 'req-1', user_name: 'Davids Ogan', created_at: '2026-06-22 11:30' },
  { id: 'act-3', activity_type: 'goal_milestone', description: 'Emeka Nwosu submitted Strategy iteration for unified mode-ops codebase', entity_type: 'Goal', entity_id: 'g2', user_name: 'Emeka Nwosu', created_at: '2026-06-23 15:45' },
  { id: 'act-4', activity_type: 'crm_lead', description: 'New international lead captured from UK: UK Trade Connect (GBP 5,200)', entity_type: 'Lead', entity_id: 'l5', user_name: 'Chioma Eze', created_at: '2026-06-24 09:20' },
];

export const initialNotifications: AppNotification[] = [
  { id: 'notif-1', user_id: 'u1', type: 'expense', title: 'New Requisition Pending', message: 'Chioma Eze requested ₦250,000 for Q3 Marketing & Meta Ads spend.', link_url: '/dashboard/expenses', read: false, created_at: '2026-06-25T09:45:00Z' },
  { id: 'notif-2', user_id: 'u1', type: 'hosting', title: 'Domain Renewal Approaching', message: 'edufirst.ng expires in under 15 days. Auto-renew is turned OFF.', link_url: '/dashboard/crm/hosting', read: false, created_at: '2026-06-25T11:00:00Z' },
  { id: 'notif-3', user_id: 'u2', type: 'feedback', title: 'New One-Minute Praise!', message: 'Davids Ogan sent you praise regarding the UK Trade deal.', link_url: '/dashboard/omm/feedback', read: true, created_at: '2026-06-15T14:30:00Z' },
];

export const initialPayrollRecords: PayrollRecord[] = [
  {
    id: 'payr-1',
    staffId: 'u1',
    staffName: 'Davids Ogan',
    staffEmail: 'info@modedigitalcreations.ng',
    department: 'Executive',
    jobTitle: 'Managing Director & Founder',
    period: 'September 2026',
    payDate: '2026-09-28',
    currency: 'NGN',
    baseSalary: 950000,
    allowances: { housing: 200000, transport: 100000, utility: 50000 },
    bonuses: 0,
    grossPay: 1300000,
    deductions: { tax: 88000, pension: 45000, healthInsurance: 15000 },
    totalDeductions: 148000,
    netPay: 1152000,
    paymentMethod: 'bank_transfer',
    bankName: 'Stanbic IBTC Bank',
    accountNumber: '0028918291',
    accountName: 'Davids Ogan',
    status: 'paid',
    approvedBy: 'Davids Ogan',
    approvedAt: '2026-09-27T10:00:00Z',
    paidAt: '2026-09-28T09:15:00Z',
    notes: 'Executive salary processed via Stanbic Corporate ACH.',
    createdAt: '2026-09-25',
  },
  {
    id: 'payr-2',
    staffId: 'u3',
    staffName: 'Emeka Nwosu',
    staffEmail: 'emeka@modedigitalcreations.ng',
    department: 'Engineering',
    jobTitle: 'Senior Full-Stack Engineer',
    period: 'September 2026',
    payDate: '2026-09-28',
    currency: 'NGN',
    baseSalary: 650000,
    allowances: { housing: 120000, transport: 60000, utility: 20000 },
    bonuses: 50000,
    grossPay: 900000,
    deductions: { tax: 58000, pension: 36000, healthInsurance: 12000 },
    totalDeductions: 106000,
    netPay: 794000,
    paymentMethod: 'bank_transfer',
    bankName: 'Guaranty Trust Bank (GTB)',
    accountNumber: '0148927110',
    accountName: 'Emeka Nwosu',
    status: 'paid',
    approvedBy: 'Davids Ogan',
    approvedAt: '2026-09-27T10:00:00Z',
    paidAt: '2026-09-28T09:15:00Z',
    notes: 'Includes Q3 code deployment bonus.',
    createdAt: '2026-09-25',
  },
  {
    id: 'payr-3',
    staffId: 'u2',
    staffName: 'Chioma Eze',
    staffEmail: 'chioma@modedigitalcreations.ng',
    department: 'Sales & Growth',
    jobTitle: 'Head of Sales',
    period: 'September 2026',
    payDate: '2026-09-28',
    currency: 'NGN',
    baseSalary: 500000,
    allowances: { housing: 100000, transport: 50000, utility: 15000 },
    bonuses: 120000,
    grossPay: 785000,
    deductions: { tax: 46000, pension: 28000, healthInsurance: 10000 },
    totalDeductions: 84000,
    netPay: 701000,
    paymentMethod: 'bank_transfer',
    bankName: 'Zenith Bank',
    accountNumber: '2108829910',
    accountName: 'Chioma Eze',
    status: 'paid',
    approvedBy: 'Davids Ogan',
    approvedAt: '2026-09-27T10:00:00Z',
    paidAt: '2026-09-28T09:15:00Z',
    notes: 'Includes closed deals commission for FashionHub.',
    createdAt: '2026-09-25',
  },
  {
    id: 'payr-4',
    staffId: 'u4',
    staffName: 'Fatima Bello',
    staffEmail: 'fatima@modedigitalcreations.ng',
    department: 'Operations',
    jobTitle: 'Operations & Project Manager',
    period: 'September 2026',
    payDate: '2026-09-28',
    currency: 'NGN',
    baseSalary: 520000,
    allowances: { housing: 100000, transport: 50000, utility: 15000 },
    bonuses: 0,
    grossPay: 685000,
    deductions: { tax: 42000, pension: 26000, healthInsurance: 10000 },
    totalDeductions: 78000,
    netPay: 607000,
    paymentMethod: 'bank_transfer',
    bankName: 'Access Bank',
    accountNumber: '0039281722',
    accountName: 'Fatima Bello',
    status: 'paid',
    approvedBy: 'Davids Ogan',
    approvedAt: '2026-09-27T10:00:00Z',
    paidAt: '2026-09-28T09:15:00Z',
    notes: 'Operations lead monthly compensation.',
    createdAt: '2026-09-25',
  },
  {
    id: 'payr-5',
    staffId: 'u5',
    staffName: 'Ibrahim Musa',
    staffEmail: 'ibrahim@modedigitalcreations.ng',
    department: 'Administration',
    jobTitle: 'Administration & Finance Lead',
    period: 'September 2026',
    payDate: '2026-09-28',
    currency: 'NGN',
    baseSalary: 450000,
    allowances: { housing: 80000, transport: 40000, utility: 15000 },
    bonuses: 0,
    grossPay: 585000,
    deductions: { tax: 35000, pension: 22000, healthInsurance: 10000 },
    totalDeductions: 67000,
    netPay: 518000,
    paymentMethod: 'bank_transfer',
    bankName: 'First Bank of Nigeria',
    accountNumber: '3029182741',
    accountName: 'Ibrahim Musa',
    status: 'paid',
    approvedBy: 'Davids Ogan',
    approvedAt: '2026-09-27T10:00:00Z',
    paidAt: '2026-09-28T09:15:00Z',
    notes: 'Administration and finance lead monthly compensation.',
    createdAt: '2026-09-25',
  },
];

// ==========================================
// DAILY STAFF SHIFTS & ATTENDANCE
// ==========================================
export const initialShifts: StaffShift[] = [
  {
    id: 'shift-101',
    staffId: 'u2',
    staffName: 'Chioma Eze',
    staffEmail: 'chioma@modedigitalcreations.ng',
    department: 'Sales & Growth',
    jobTitle: 'Head of Sales',
    date: '2026-09-30',
    clockInTime: '2026-09-30T08:15:00Z',
    clockOutTime: '2026-09-30T16:30:00Z',
    durationHours: 8.25,
    status: 'completed',
    hourlyRate: 2800,
    notes: 'Shift completed: Client proposal closing calls & pipeline review.'
  },
  {
    id: 'shift-102',
    staffId: 'u3',
    staffName: 'Emeka Nwosu',
    staffEmail: 'emeka@modedigitalcreations.ng',
    department: 'Engineering',
    jobTitle: 'Senior Full-Stack Engineer',
    date: '2026-09-30',
    clockInTime: '2026-09-30T08:30:00Z',
    clockOutTime: '2026-09-30T16:30:00Z',
    durationHours: 8.0,
    status: 'completed',
    hourlyRate: 3500,
    notes: 'Shift completed: ModeCBT testing engine deployment & Next.js Turbopack fixes.'
  },
  {
    id: 'shift-103',
    staffId: 'u4',
    staffName: 'Fatima Bello',
    staffEmail: 'fatima@modedigitalcreations.ng',
    department: 'Operations',
    jobTitle: 'Operations & Project Manager',
    date: '2026-09-30',
    clockInTime: '2026-09-30T08:45:00Z',
    clockOutTime: '2026-09-30T16:30:00Z',
    durationHours: 7.75,
    status: 'completed',
    hourlyRate: 3000,
    notes: 'Shift completed: Operations sync, staff goals vetting, and sprint milestones.'
  },
  {
    id: 'shift-104',
    staffId: 'u5',
    staffName: 'Ibrahim Musa',
    staffEmail: 'admin@modedigitalcreations.ng',
    department: 'Administration',
    jobTitle: 'Administration & Finance Lead',
    date: '2026-09-30',
    clockInTime: '2026-09-30T09:00:00Z',
    clockOutTime: '2026-09-30T17:00:00Z',
    durationHours: 8.0,
    status: 'completed',
    hourlyRate: 2500,
    notes: 'Shift completed: Office administration, requisition disbursement, vouchers and accounts audit.'
  },
  {
    id: 'shift-105',
    staffId: 'u1',
    staffName: 'Davids Ogan',
    staffEmail: 'info@modedigitalcreations.ng',
    department: 'Executive',
    jobTitle: 'Managing Director & Founder',
    date: '2026-09-30',
    clockInTime: '2026-09-30T07:45:00Z',
    clockOutTime: '2026-09-30T16:30:00Z',
    durationHours: 8.75,
    status: 'completed',
    hourlyRate: 5000,
    notes: 'Managing Director daily executive shift & corporate governance.'
  },
  // Previous Day Completed Shifts
  {
    id: 'shift-099',
    staffId: 'u2',
    staffName: 'Chioma Eze',
    staffEmail: 'chioma@modedigitalcreations.ng',
    department: 'Sales & Growth',
    jobTitle: 'Head of Sales',
    date: '2026-09-29',
    clockInTime: '2026-09-29T08:20:00Z',
    clockOutTime: '2026-09-29T17:35:00Z',
    durationHours: 9.25,
    status: 'completed',
    hourlyRate: 2800,
    notes: 'Full shift: Sahara Logistics negotiation and UK Trade Connect proposals.'
  },
  {
    id: 'shift-098',
    staffId: 'u3',
    staffName: 'Emeka Nwosu',
    staffEmail: 'emeka@modedigitalcreations.ng',
    department: 'Engineering',
    jobTitle: 'Senior Full-Stack Engineer',
    date: '2026-09-29',
    clockInTime: '2026-09-29T08:30:00Z',
    clockOutTime: '2026-09-29T18:00:00Z',
    durationHours: 9.5,
    status: 'completed',
    hourlyRate: 3500,
    notes: 'Full shift + 1.5h Overtime: Supabase schema migration and API endpoint hardening.'
  },
  {
    id: 'shift-097',
    staffId: 'u4',
    staffName: 'Fatima Bello',
    staffEmail: 'fatima@modedigitalcreations.ng',
    department: 'Operations',
    jobTitle: 'Operations & Project Manager',
    date: '2026-09-29',
    clockInTime: '2026-09-29T08:40:00Z',
    clockOutTime: '2026-09-29T17:10:00Z',
    durationHours: 8.5,
    status: 'completed',
    hourlyRate: 3000,
    notes: 'Standard shift: Requisition sign-offs and client project milestone check.'
  },
  {
    id: 'shift-096',
    staffId: 'u5',
    staffName: 'Ibrahim Musa',
    staffEmail: 'ibrahim@modedigitalcreations.ng',
    department: 'Administration',
    jobTitle: 'Administration & Finance Lead',
    date: '2026-09-29',
    clockInTime: '2026-09-29T09:05:00Z',
    clockOutTime: '2026-09-29T17:20:00Z',
    durationHours: 8.25,
    status: 'completed',
    hourlyRate: 2500,
    notes: 'Standard shift: Monthly payroll dispatches, bank reconciliations.'
  }
];

export const initialMemos: StaffMemo[] = [
  {
    id: 'memo-001',
    memoNumber: 'MEMO-2026-001',
    title: 'URGENT: Public Holiday Office Schedule & Emergency Standby Rotations',
    content: `All Team Members,\n\nPlease be informed of our operational schedule for the upcoming public holiday. While physical operations will observe the national holiday, the Web Hosting Infrastructure and Client Support desk will maintain active on-call coverage to guarantee 99.9% uptime for all client portals and WHMCS provisioning.\n\nKey Directives:\n1. Technical Support & Systems Specialists (Ben Asiedu & Emeka Nwosu) will monitor automated server health alerts on rotating shifts.\n2. Any emergency client escalations received via WhatsApp or support ticket must be responded to within 30 minutes.\n3. Daily shift clock-in remains mandatory for staff working remote standby.\n\nPlease read and acknowledge this memo below immediately.`,
    senderId: 'u1',
    senderName: 'Davids Ogan',
    senderRole: 'managing_director',
    senderDepartment: 'Executive',
    targetAudience: 'all',
    priority: 'urgent',
    category: 'urgent_notice',
    requiresAcknowledgment: true,
    readBy: {
      'u1': '2026-09-30T08:00:00Z',
      'u4': '2026-09-30T09:15:00Z',
      'u5': '2026-09-30T10:00:00Z'
    },
    acknowledgedBy: {
      'u1': '2026-09-30T08:00:00Z',
      'u4': '2026-09-30T09:20:00Z'
    },
    createdAt: '2026-09-30T07:45:00Z'
  },
  {
    id: 'memo-002',
    memoNumber: 'MEMO-2026-002',
    title: 'Standard Operating Procedures for Client Hosting & Server Deployments',
    content: `Attention All Engineering & Hosting Staff,\n\nEffective immediately, the following protocol must be strictly observed prior to deploying updates or provisioning live hosting accounts for corporate clients:\n\n1. Staging Verification: All website and web application code must undergo end-to-end testing in the local/staging environment before pushing to client production servers.\n2. WHMCS Synchronization: Domain registrations, SSL certificate certificates, and monthly renewals must be reconciled via the MODE Ops WHMCS live API integration.\n3. Zero Unscheduled Downtime: Maintenance windows must be announced to clients with at least 48 hours prior notification.\n\nManagement expects strict compliance from all technical personnel.`,
    senderId: 'u4',
    senderName: 'Fatima Bello',
    senderRole: 'manager',
    senderDepartment: 'Operations',
    targetAudience: 'all',
    priority: 'policy',
    category: 'policy',
    requiresAcknowledgment: true,
    readBy: {
      'u1': '2026-09-28T11:00:00Z',
      'u3': '2026-09-28T14:30:00Z',
      'u7': '2026-09-28T16:00:00Z'
    },
    acknowledgedBy: {
      'u1': '2026-09-28T11:05:00Z',
      'u3': '2026-09-28T14:45:00Z'
    },
    createdAt: '2026-09-28T10:00:00Z'
  },
  {
    id: 'memo-003',
    memoNumber: 'MEMO-2026-003',
    title: 'Q4 2026 Operations & Client Deliverables Strategic Alignment',
    content: `Dear Team,\n\nAs we enter the final quarter of 2026, I want to commend the entire MODE Digital Creations & Mode Web Host team for our stellar client delivery and expanded sales pipeline.\n\nOur top priorities for Q4:\n• Accelerate close rate on active corporate proposals (TechVenture, Sahara Logistics, EduFirst).\n• Maintain strict adherence to daily shift attendance logging; verified shift hours directly feed into your monthly payroll disbursement.\n• Ensure prompt processing of office expense requisitions with valid vendor receipts.\n\nManagement has instituted end-of-year performance bonuses tied to goal completions logged through our One-Minute Leadership framework. Let us stay focused and close the year with excellence!`,
    senderId: 'u1',
    senderName: 'Davids Ogan',
    senderRole: 'managing_director',
    senderDepartment: 'Executive',
    targetAudience: 'all',
    priority: 'announcement',
    category: 'operations',
    requiresAcknowledgment: false,
    readBy: {
      'u1': '2026-09-25T09:00:00Z',
      'u2': '2026-09-25T11:20:00Z',
      'u3': '2026-09-25T12:00:00Z',
      'u4': '2026-09-25T13:40:00Z'
    },
    acknowledgedBy: {
      'u1': '2026-09-25T09:00:00Z',
      'u2': '2026-09-25T11:25:00Z'
    },
    createdAt: '2026-09-25T08:30:00Z'
  }
];

